cart/urls.py
from django.urls import path

from . import views
from .apps import CartConfig

app_name = CartConfig.name

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:pk>/', views.cart_add, name='cart_add'),
    path('remove/<int:pk>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('bakery.urls', namespace='bakery')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from . import views
from django.urls import path
from .apps import OrdersConfig

app_name = OrdersConfig.name

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.forms import BooleanField

from bakery.forms import StyleFormMixin

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(StyleFormMixin, forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from bakery.models import Products
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, pk):
    product_pk = pk
    print(f'pk={product_pk}')
    cart = Cart(request)
    product = get_object_or_404(Products, pk=product_pk)
    print(product)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, pk):
    cart = Cart(request)
    product = get_object_or_404(Products, id=pk)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
<!DOCTYPE html>
{% load mediapath_tag %}
{% load static %}
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Bakery</title>
    <meta name="description" content="">
    <meta name="keywords" content="">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">

    <!-- Main CSS File -->
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
</head>
<body class="index-page">

<header id="header" class="header d-flex align-items-center sticky-top">
    {% include 'bakery/includes/main_menu_product.html' %}
</header>

    <div class="container p-5">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text">Ваш Заказ</span>
        {% with total_items=cart|length %}
        <span class="badge rounded-pill" style="background-color:#2c6861;">{{ total_items }}</span>
        {% endwith %}
    </h4>
    <ul class="list-group mb-3">
        {% for item in cart %}
        {% with product=item.product %}
        <li class="list-group-item d-flex justify-content-between lh-sm">
            <div class="container p-0">
                <div class="position-relative">
                    <div class="position-absolute top-0 end-0">
                        <a type="button" class="btn-close" aria-label="Close"
                           href="{% url 'cart:cart_remove' product.pk %}"> </a>
                    </div>
                </div>
                <div class="row justify-content-between">
                    <div class="col-md-auto">
                        <img src="{% mediapath product.img %}" class="rounded float-start img-fluid" alt="...">
                    </div>
                    <div class="col-md-auto">
                        <h6 class="my-0">{{ product.name }}</h6>
                        <small class="text-body-secondary">{{ product.weight }} г</small><br>
                        <small class="text-body-secondary">кол-во: {{ item.quantity }}</small>
                    </div>
                    <div class="col-md-auto pr-0 align-self-end">
                        <span class="text-body-secondary">
                            ₽{{ item.total_price }}
                        </span>
                    </div>
                </div>
            </div>
        </li>
        {% endwith %}
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between">
            <span>Итого</span>
            <strong>₽{{ cart.get_total_price }}</strong>
        </li>
    </ul>
        <div class="container">
            <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Оформить заказ</a>
        </div>
</div>



{% include 'bakery/includes/footer.html' %}

<!-- Scroll Top -->
<a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Preloader -->
<div id="preloader"></div>

<!-- Vendor JS Files -->
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
<script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
<script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'assets/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>

<!-- Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>