bakery/urls.py
from django.urls import path

from bakery.apps import BakeryConfig
from bakery.views import ProductView, ProductFilterView, CategoryCreate, ProductDetailView, ProductCreateView, \
    ProductUpdateView, ProductDeleteView

app_name = BakeryConfig.name

urlpatterns = [
    path('', ProductView.as_view(), name='index'),
    path('products/<int:pk>/', ProductFilterView.as_view(), name='product_filter'),
    path('create_category/', CategoryCreate.as_view(), name='category'),
    path('<int:pk>/', ProductDetailView.as_view(), name='product_info'),
    path('create_product/', ProductCreateView.as_view(), name='product_create'),
    path('update_product/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('delete_product/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
]

cart/urls.py
from django.urls import path

from . import views
from .apps import CartConfig

app_name = CartConfig.name

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:pk>/', views.cart_add, name='cart_add'),
    path('remove/<int:pk>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('bakery.urls', namespace='bakery')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bakery/models.py
from django.db import models


class Category(models.Model):

    name = models.CharField(verbose_name='Название', max_length=50, null=True, blank=True)
    about = models.TextField(verbose_name='Описание', null=True, blank=True)

    def __str__(self):
        return f'Категория: {self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Products(models.Model):
    CAKE = 'cake'
    FROST = 'frost'
    MINI_CAKE = 'mini_cake'

    CHOICE_GROUP = {
        (CAKE, 'cake'),
        (FROST, 'frost'),
        (MINI_CAKE, 'mini_cake'),
    }

    name = models.CharField(max_length=60, verbose_name='Название', null=True, blank='True')
    img = models.ImageField(upload_to='products', verbose_name='Изображение', null=True, blank=True)
    price = models.FloatField(verbose_name='Цена', null=True, blank='True')
    weight = models.FloatField(verbose_name='Вес', null=True, blank='True')
    description = models.TextField(verbose_name='Описание', null=True, blank='True')
    content = models.TextField(verbose_name='Состав', null=True, blank=True)
    nutritional_value = models.TextField(verbose_name='Пищевая ценность', null=True, blank=True)
    product_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    category_filter = models.CharField(max_length=20, choices=CHOICE_GROUP, default=CAKE)
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')

    def __str__(self):
        return f'{self.product_category} {self.name}'

    class Meta:
        verbose_name = 'продукция'
        verbose_name_plural = 'продукции'

bakery/forms.py
from django import forms
from django.forms import BooleanField

from bakery.models import Products, Category


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super(StyleFormMixin, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class CategoryForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Products
        fields = '__all__'


class ProductDescriptionForm(ProductForm):
    class Meta:
        model = Products
        fields = ('description', 'product_category', 'is_published')

bakery/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from bakery.forms import ProductDescriptionForm, CategoryForm, ProductForm
from bakery.models import Products, Category
from cart.forms import CartAddProductForm


class ProductView(ListView):
    model = Products
    template_name = 'bakery/index.html'

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super(ProductView, self).get_context_data(**kwargs)
    #     context['category'] = Category.objects.all()
    #     return context


class ProductFilterView(ListView):
    model = Products
    template_name = 'bakery/index.html'
    allow_empty = False

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductFilterView, self).get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context

    def get_queryset(self):
        self.category = get_object_or_404(Category, pk=self.kwargs['pk'])
        print(self.category)
        return Products.objects.filter(product_category=self.category)


class ProductDetailView(DetailView):
    model = Products
    template_name = 'bakery/product_info.html'

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['cart_product_form'] = CartAddProductForm()
        return context


class ProductCreateView(CreateView):
    model = Products
    form_class = ProductForm
    success_url = reverse_lazy('bakery:index')


class ProductUpdateView(UpdateView):
    model = Products
    form_class = ProductForm
    success_url = reverse_lazy('bakery:index')

    def form_valid(self, form):
        context_data = self.get_context_data()

        if form.is_valid():
            self.object = form.save()
            return super(ProductUpdateView, self).form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))


class ProductDeleteView(DeleteView):
    model = Products
    success_url = reverse_lazy('bakery:index')



class CategoryCreate(CreateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('bakery:index')

bakery/templates/bakery/includes/category_menu.html
<div class="container p-2" id="menu_category">
    {% for item in category %}
    <a category={{ item.name }} href="{% url 'bakery:product_filter' item.pk %}" class="btn btn-lg"
       aria-pressed="true">{{ item.name }}</a>
    {% endfor %}
</div>

bakery/templates/bakery/includes/footer.html
<footer id="footer" class="footer dark-background">

    <div class="container">
        <div class="row gy-3">
            <div class="col-lg-3 col-md-6 d-flex">
                <i class="bi bi-geo-alt icon"></i>
                <div class="address">
                    <h4>Address</h4>
                    <p>A108 Adam Street</p>
                    <p>New York, NY 535022</p>
                    <p></p>
                </div>

            </div>

            <div class="col-lg-3 col-md-6 d-flex">
                <i class="bi bi-telephone icon"></i>
                <div>
                    <h4>Contact</h4>
                    <p>
                        <strong>Phone:</strong> <span>+1 5589 55488 55</span><br>
                        <strong>Email:</strong> <span>info@example.com</span><br>
                    </p>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 d-flex">
                <i class="bi bi-clock icon"></i>
                <div>
                    <h4>Opening Hours</h4>
                    <p>
                        <strong>Mon-Sat:</strong> <span>11AM - 23PM</span><br>
                        <strong>Sunday</strong>: <span>Closed</span>
                    </p>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <h4>Follow Us</h4>
                <div class="social-links d-flex">
                    <a href="#" class="twitter"><i class="bi bi-twitter-x"></i></a>
                    <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                    <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                    <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                </div>
            </div>

        </div>
    </div>

    <div class="container copyright text-center mt-4">
        <p>© <span>Copyright</span> <strong class="px-1 sitename">Bakery</strong> <span>All Rights Reserved</span></p>
    </div>

</footer>

bakery/templates/bakery/includes/main_menu.html
{% load mediapath_tag %}
<div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

    <a href="{% url 'bakery:index'%}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
<!--        <img src="assets/img/logo.png" alt="">-->
        <h1 class="sitename">Bakery</h1>
    </a>

    <nav id="navmenu" class="navmenu">
        <ul>
            <li><a href="#hero" class="active">Home</a></li>
            <li><a href="#about">Мастерклассы</a></li>
            <li><a href="#services">Повар на дом</a></li>
            <li><a href="#portfolio">Продукция</a></li>
            <li><a href="#team">Контакты</a></li>
            <li><a href="#contact">Contact</a></li>
            <li>
                <div class="dropdown">
                    <a class="bi bi-cart dropdown-toggle w-auto h-auto" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false"></a>
                    <ul class="dropdown-menu p-3">
                        {% for item in cart %}
                        {% with product=item.product %}
                            <li class="list-group-item d-flex justify-content-between lh-sm border-bottom mb-2">
                                <div class="container p-0">
                                    <div class="position-relative">
                                        <div class="position-absolute top-0 end-0">
                                            <a type="button" class="btn-close" aria-label="Close"
                                               href="{% url 'cart:cart_remove' product.pk %}"> </a>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <img src="{% mediapath product.img %}" class="rounded float-start img-fluid" alt="...">
                                        </div>
                                        <div class="col-auto">
                                            <p class="text-body-secondary">{{ product.name }}</p><br>
                                            <small class="text-body-secondary">{{ product.weight }} г</small><br>
                                            <small class="text-body-secondary">кол-во: {{ item.quantity }}</small>
                                        </div>
                                        <div class="col-auto pr-0 align-self-end">
                                                <span class="text-body-secondary">
                                                   ₽{{ item.total_price }}
                                                </span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% endwith %}
                    {% endfor %}
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Итого</span>
                        <strong>₽{{ cart.get_total_price }}</strong>
                    </li>
                        <li class="list-group-item d-flex justify-content-between">
                            <a  class="btn btn-outline-dark m-1" href="{% url 'cart:cart_detail' %}">
                            Оформить заказа
                            </a>
                            <a  class="btn btn-outline-dark m-1" href="{% url 'cart:cart_detail' %}">
                            Перейти в корзину
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
    </nav>


</div>

bakery/templates/bakery/includes/main_menu_product.html
<div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

    <a href="{% url 'bakery:index'%}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!--<img src="assets/img/logo.png" alt="">-->
        <h1 class="sitename">Bakery</h1>
    </a>

    <nav id="navmenu" class="navmenu">
        <ul>
            <li><a href="{% url 'bakery:index'%}" class="active">Home</a></li>
            <li><a href="{% url 'bakery:index'%}#about">Мастерклассы</a></li>
            <li><a href="{% url 'bakery:index'%}#services">Повар на дом</a></li>
            <li><a href="{% url 'bakery:index'%}#portfolio">Продукция</a></li>
            <li><a href="{% url 'bakery:index'%}#team">Контакты</a></li>
            <li><a href="{% url 'bakery:index'%}#contact">Contact</a></li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
    </nav>

</div>